version: '3.8'

services:
  # --- INFRASTRUCTURE SERVICES ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
    networks:
      - app_network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: always
    ports:
      - 6432:6432
    environment:
      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/postgres_db
      - DEFAULT_POOL_SIZE=20
      - MAX_CLIENT_CONN=1000
      - POOL_MODE=transaction
      - AUTH_TYPE=any
    depends_on:
      - postgres
    networks:
      - app_network

  mongodb-primary:
    container_name: mongodb-primary
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    networks:
      - app_network

  mongodb-secondary:
    container_name: mongodb-secondary
    image: mongo
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-secondary
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: example
    networks:
      - app_network

  mongodb-arbiter:
    container_name: mongodb-arbiter
    image: mongo
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-arbiter
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: example
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb-primary:27017/
    depends_on:
      - mongodb-primary
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data
    networks:
      - app_network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniostorage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - app_network

  # --- MICROSERVICES ---
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=api-gateway
    env_file:
      - "apps/api-gateway/.env.docker"
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mongodb-primary
    networks:
      - app_network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=authentication
    env_file:
      - "apps/authentication/.env.docker"
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    networks:
      - app_network

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=users
    env_file:
      - "apps/users/.env.docker"
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app_network

  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=products
    env_file:
      - "apps/products/.env.docker"
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
      - mongodb-primary
    networks:
      - app_network

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=orders
    env_file:
      - "apps/orders/.env.docker"
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app_network

  payment-service:
    container_name: payment-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=payments
    env_file:
      - "apps/payments/.env.docker"
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app_network

volumes:
  redis_data_container:
    driver: local
  mongodb_data_container:
    driver: local
  miniostorage:
    driver: local
  postgres_data_container:
    driver: local

networks:
  app_network:
    driver: bridge
